import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Blog by Elias Grinwis Plaat Stultjes",
  description: "Generated by Elias Grinwis Plaat Stultjes",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl">
      <body className={` ${inter.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
